version: "3"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - valar_morghulis_db:/var/lib/postgresql/data

  backend:
    image: valar_morghulis_api:latest
    build: .
    environment:
      POSTGRES_HOST: "db"
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:8080", "http://localhost:3000"]'

    ports:
      - 8080:80
    links:
      - db

volumes:
  valar_morghulis_db:
