version: "3"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - valar_morghulis_db:/var/lib/postgresql/data
      - ./scripts/initdb:/docker-entrypoint-initdb.d

  backend:
    image: valar_morghulis_api:latest
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
    ports:
      - 8080:80
    links:
      - db

volumes:
  valar_morghulis_db:
