"""create_full_database_fix

Revision ID: 496ab12f7ccb
Revises: 3ab6f8ad3b40
Create Date: 2020-06-26 00:30:55.406148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496ab12f7ccb'
down_revision = '3ab6f8ad3b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
