"""update_article

Revision ID: 712d2d7101a3
Revises: dadfd0e919f1
Create Date: 2020-06-30 17:23:20.096880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712d2d7101a3'
down_revision = 'dadfd0e919f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
