"""create_full_database_fix

Revision ID: 3ab6f8ad3b40
Revises: 939da43d4127
Create Date: 2020-06-26 00:24:27.878639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab6f8ad3b40'
down_revision = '939da43d4127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
