"""create_full_database_fix

Revision ID: 939da43d4127
Revises: c363bc6838de
Create Date: 2020-06-26 00:23:26.612227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939da43d4127'
down_revision = 'c363bc6838de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
