---
- hosts: all
  gather_facts: no
  tasks:
    - name: Ensure project directory exists
      file:
        state: directory
        path: "{{ project_name }}"

    - name: Ensure traefik directory exists
      file:
        state: directory
        path: "{{ traefik_dir }}"

    - name: Ensure acme.json file exists
      file:
        state: touch
        path: "{{ traefik_acme_file_path }}"
        mode: 0600
        access_time: preserve
        modification_time: preserve

    - name: Configure static config
      template:
        src: traefik.yml.j2
        dest: "{{ traefik_config_path }}"
      register: traefik_config_file

    - name: Copy docker-compose.yml
      template:
        src: docker-compose.yml.j2
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Login to Scaleway's registry container
      docker_login:
        registry: "{{ scw_registry_endpoint }}"
        username: nologin
        password: "{{ scw_api_token }}"

    - name: Start project
      docker_compose:
        project_src: "{{ project_dir }}"
        remove_orphans: yes
        restarted: "{{ traefik_config_file.changed }}"
